language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "8"
  - "10"
  
after_success:
  - bash <(curl -s https://codecov.io/bash)